version: '3'
services:
  php7:
    build:
        context: "./docker/php"
        dockerfile: "Dockerfile"    
    ports:
        - "80:80"
    environment:
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PASS
    volumes:
        - .:/var/www/html
    networks:
     - js
     
  node:
    build:
        context: "./docker/node"
        dockerfile: "Dockerfile"
    volumes:
        - .:/var/www/html
    tty: true
    ports:
        - "3000:3000"
    networks:
      - js

  db:
    build:
        context: "./docker/mysql"
        dockerfile: "Dockerfile"
    ports:
     - "3306:3306"
    environment:
      MYSQL_DATABASE: postcode
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./docker/mysql/init/:/docker-entrypoint-initdb.d/
    networks:
      - js


networks:
  js:
    driver: "bridge"
